# Generated by Django 3.0 on 2019-12-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='tanggal',
            field=models.DateField(auto_now=True, verbose_name='Tanggal'),
        ),
    ]
